use_frameworks!

target 'HFSwipeView_Example' do
  pod 'HFSwipeView', :path => '../'

  target 'HFSwipeView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
