use_frameworks!

target 'HFSwipeView_Example' do
  pod 'HFSwipeView', :path => '../'

  target 'HFSwipeView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'HFCore'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '-D' 'DEBUG'
                    else
                    config.build_settings['OTHER_SWIFT_FLAGS'] = ''
                end
            end
        end
    end
end